import { existsSync } from 'node:fs'
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { STAGE_CVAR_NAMES, createCvarRestore, nodeCvarRestoreFs, sessionConfigPath } from './session-cvar-restore'

/** Story 170 D3: the stage cvars' snapshot/restore, against real files in a temp dir. */

let tmp: string
let configPath: string
let pendingPath: string

beforeEach(async () => {
  tmp = await mkdtemp(join(tmpdir(), 'cvar-restore-'))
  await mkdir(join(tmp, 'baseq2'))
  configPath = join(tmp, 'baseq2', 'q2config.cfg')
  pendingPath = join(tmp, 'userData', 'pending.json')
})

afterEach(async () => {
  await rm(tmp, { recursive: true, force: true })
})

const restorer = () => createCvarRestore({ names: STAGE_CVAR_NAMES, pendingPath })
const bytes = (text: string): Buffer => Buffer.from(text, 'latin1')
const readBytes = (): Promise<Buffer> => readFile(configPath)

describe('session cvar restore (story 170 D3)', () => {
  it('restores vid_fullscreen and vid_geometry lines byte-exact', async () => {
    const before =
      '// generated by q2pro\r\nset name "Pl\xe4yer"\r\nset vid_fullscreen "1"\r\n  seta vid_geometry "1920x1080+0+0"\r\nset gl_swapinterval "1"\r\n'
    await writeFile(configPath, bytes(before))
    const cvars = restorer()
    await cvars.snapshot(configPath)
    expect(existsSync(pendingPath)).toBe(true)
    // What the engine writes on exit after a stage session.
    await writeFile(
      configPath,
      bytes('// generated by q2pro\r\nset name "Pl\xe4yer"\r\nset vid_fullscreen "0"\r\nset vid_geometry "640x360+10+20"\r\nset gl_swapinterval "1"\r\n'),
    )
    await cvars.restore()
    expect((await readBytes()).equals(bytes(before))).toBe(true)
    expect(existsSync(pendingPath)).toBe(false)
  })

  it('removes a cvar that was absent before', async () => {
    const before = 'set name "a"\nset vid_fullscreen "1"\n'
    await writeFile(configPath, bytes(before))
    const cvars = restorer()
    await cvars.snapshot(configPath)
    await writeFile(configPath, bytes('set name "a"\nset vid_fullscreen "0"\nset vid_geometry "640x360+10+20"\n'))
    await cvars.restore()
    expect((await readBytes()).toString('latin1')).toBe(before)
  })

  it('removes both when the file did not exist before the session', async () => {
    const cvars = restorer()
    await cvars.snapshot(configPath)
    await writeFile(configPath, bytes('set vid_fullscreen "0"\r\nset name "a"\r\nset vid_geometry "640x360+10+20"'))
    await cvars.restore()
    expect((await readBytes()).toString('latin1')).toBe('set name "a"\r\n')
  })

  it('keeps the user\'s in-session changes', async () => {
    await writeFile(configPath, bytes('set sensitivity "3"\r\nset vid_fullscreen "1"\r\nset vid_geometry "1920x1080+0+0"\r\n'))
    const cvars = restorer()
    await cvars.snapshot(configPath)
    await writeFile(
      configPath,
      bytes('set sensitivity "5"\r\nset vid_fullscreen "0"\r\nset vid_geometry "640x360+10+20"\r\nset cl_new "1"\r\n'),
    )
    await cvars.restore()
    expect((await readBytes()).toString('latin1')).toBe(
      'set sensitivity "5"\r\nset vid_fullscreen "1"\r\nset vid_geometry "1920x1080+0+0"\r\nset cl_new "1"\r\n',
    )
  })

  it('puts back a line the engine dropped, with the file\'s own line ending', async () => {
    await writeFile(configPath, bytes('set a "1"\r\nset vid_fullscreen "1"\r\n'))
    const cvars = restorer()
    await cvars.snapshot(configPath)
    await writeFile(configPath, bytes('set a "2"\r\nset b "3"'))
    await cvars.restore()
    expect((await readBytes()).toString('latin1')).toBe('set a "2"\r\nset b "3"\r\nset vid_fullscreen "1"\r\n')
  })

  it('a missing file does nothing', async () => {
    await writeFile(configPath, bytes('set vid_fullscreen "1"\n'))
    const cvars = restorer()
    await cvars.snapshot(configPath)
    await rm(configPath)
    await cvars.restore()
    expect(existsSync(configPath)).toBe(false)
    expect(existsSync(pendingPath)).toBe(false)
  })

  it('applies a pending snapshot at start', async () => {
    const before = 'set vid_fullscreen "1"\r\nset name "a"\r\n'
    await writeFile(configPath, bytes(before))
    // A launcher that crashed mid-session: snapshot taken, restore never ran.
    await restorer().snapshot(configPath)
    await writeFile(configPath, bytes('set vid_fullscreen "0"\r\nset name "b"\r\nset vid_geometry "640x360+10+20"\r\n'))

    const next = restorer()
    await next.applyPending()
    expect((await readBytes()).toString('latin1')).toBe('set vid_fullscreen "1"\r\nset name "b"\r\n')
    expect(existsSync(pendingPath)).toBe(false)
    // Once only: nothing is pending any more.
    await writeFile(configPath, bytes('set vid_fullscreen "0"\r\n'))
    await next.applyPending()
    expect((await readBytes()).toString('latin1')).toBe('set vid_fullscreen "0"\r\n')
  })

  it('a pending snapshot never touches a cvar it does not own', async () => {
    await mkdir(join(tmp, 'userData'))
    await writeFile(pendingPath, JSON.stringify({ configPath, lines: { name: null, vid_fullscreen: 'set vid_fullscreen "1"' } }))
    await writeFile(configPath, bytes('set name "a"\nset vid_fullscreen "0"\n'))
    await restorer().applyPending()
    expect((await readBytes()).toString('latin1')).toBe('set name "a"\nset vid_fullscreen "1"\n')
  })

  it('a restore queued before the next snapshot runs first', async () => {
    await writeFile(configPath, bytes('set vid_fullscreen "1"\n'))
    const cvars = restorer()
    await cvars.snapshot(configPath)
    await writeFile(configPath, bytes('set vid_fullscreen "0"\n'))
    // An exit immediately followed by the next stage play: neither awaited before the other starts.
    const restored = cvars.restore()
    const snapped = cvars.snapshot(configPath)
    await Promise.all([restored, snapped])
    await writeFile(configPath, bytes('set vid_fullscreen "0"\n'))
    await cvars.restore()
    expect((await readBytes()).toString('latin1')).toBe('set vid_fullscreen "1"\n')
  })

  it('a failed restore keeps the original snapshot across the next snapshot', async () => {
    const before = 'set vid_fullscreen "1"\nset vid_geometry "1920x1080+0+0"\n'
    await writeFile(configPath, bytes(before))
    let failing = true
    const fs = {
      ...nodeCvarRestoreFs,
      rename: async (from: string, to: string) => {
        if (failing && to === configPath) throw Object.assign(new Error('busy'), { code: 'EBUSY' })
        return nodeCvarRestoreFs.rename(from, to)
      },
    }
    const cvars = createCvarRestore({ names: STAGE_CVAR_NAMES, pendingPath, fs })
    await cvars.snapshot(configPath)
    const staged = 'set vid_fullscreen "0"\nset vid_geometry "640x360+10+20"\n'
    await writeFile(configPath, bytes(staged))
    await expect(cvars.restore()).rejects.toThrow('busy')
    expect(existsSync(pendingPath)).toBe(true)

    // The next play snapshots a config that still holds the stage values - it must not replace the original.
    await cvars.snapshot(configPath)
    expect((await readBytes()).toString('latin1')).toBe(staged)
    failing = false
    await cvars.restore()
    expect((await readBytes()).toString('latin1')).toBe(before)
    expect(existsSync(pendingPath)).toBe(false)
  })

  it('the config lives in the game dir, or in Q2PRO\'s Linux write dir', () => {
    const installation = { id: 'q', name: 'Q2PRO', rootPath: '/games/q2', engineKind: 'q2pro' as const, gameDirs: ['baseq2'] }
    const ctx = (platform: NodeJS.Platform) => ({
      platform,
      homeDir: '/home/u',
      zipDeps: { extractorPath: 'x', extractorExists: false },
    })
    expect(sessionConfigPath(installation, 'ctf', join('/games/q2', 'ctf'), ctx('win32'))).toBe(
      join('/games/q2', 'ctf', 'q2config.cfg'),
    )
    expect(sessionConfigPath(installation, 'ctf', join('/games/q2', 'ctf'), ctx('linux'))).toBe(
      join('/home/u', '.q2pro', 'ctf', 'q2config.cfg'),
    )
  })
})
