// Fixture seed data + writers for the UI-verification harness: a facade over the domain files in
// `./fixture/`, which hold the content. Importers keep using `./fixture.mjs`.
//
// `scripts/` is plain Node ESM outside both TS projects, so it cannot
// `import type`/`import` anything from `src/**/*.ts` at runtime. Instead, the
// small set of literal values this file needs are hardcoded below, each
// annotated with exactly the source file/constant it mirrors, so a future
// schema bump is easy to find via grep (search for "mirrors").
//
// Everything here is deterministic: fixed ids and fixed ISO timestamps, never
// `Date.now()`/`crypto.randomUUID()`. That is what makes `npm run ui:seed`

export {
  LEGACY_SEED_SCHEMA_VERSION,
  installationConfigFilePath,
  installationRootFilePath,
  installationRootPath,
  INSTALL_ONE_ID,
  INSTALL_TWO_ID,
} from './fixture/core.mjs'
export {
  NEWS_IMAGE_PRESENT_SLIDE_ID,
  NEWS_IMAGE_FAILED_SLIDE_ID,
  writeNewsImagesFixture,
  COVER_PROBE_IMAGE_WIDTH,
  COVER_PROBE_IMAGE_HEIGHT,
  COVER_PROBE_MIN_CHANNEL,
  NEWS_COVER_SLIDE_ID,
  NEWS_COVER_SLIDE_TITLE,
  writeNewsCoverFixture,
  writeNewsStaleFixture,
} from './fixture/news.mjs'
export {
  INSTALL_ONE_ICON_ID,
  INSTALL_UNKNOWN_ENGINE_NAME,
  INSTALL_FAILED_ERROR_KEY,
  INSTALL_DEMO_UPGRADE_ID,
  INSTALL_DEMO_UPGRADE_NAME,
  RETAIL_UPGRADE_MARKER_FILE,
  INSTALL_ENGINE_UPDATE_ID,
  INSTALL_ENGINE_UPDATE_NAME,
  ENGINE_UPDATE_OLD_VERSION,
  ENGINE_FIXTURE_FILES,
  ENGINE_INSTALLED_RELATIVE,
  ENGINE_UPDATE_OLD_FILL_BYTE,
  INSTALL_REPAIR_ENGINE_ID,
  INSTALL_REPAIR_ENGINE_NAME,
  INSTALL_REPAIR_POINT_RELEASE_ID,
  INSTALL_REPAIR_POINT_RELEASE_NAME,
  INSTALL_REPAIR_RETAIL_ID,
  INSTALL_REPAIR_RETAIL_NAME,
  INSTALL_REPAIR_WRITEDIR_ID,
  INSTALL_REPAIR_WRITEDIR_NAME,
  INSTALL_REPAIR_UNREPAIRABLE_ID,
  INSTALL_REPAIR_UNREPAIRABLE_NAME,
  repairNonWritableDir,
  INSTALL_REMOVE_STORE_ID,
  INSTALL_REMOVE_STORE_NAME,
  INSTALL_REMOVE_DISK_ID,
  INSTALL_REMOVE_DISK_NAME,
  installRemoveDiskSiblingSentinelPath,
  INSTALL_REMOVE_DISK_SIBLING_SENTINEL_CONTENT,
  populatedInstallationCount,
  importFilesFixturePaths,
  writeImportFilesFixture,
  LINUX_JOURNEY_INSTALL_NAME,
  linuxJourneyInstallRoot,
  linuxJourneyExecutablePath,
  writeLinuxJourneyInstallRoot,
  JOIN_INSTALL_ID,
  joinInstallRoot,
  joinExecutablePath,
  writeJoinInstallRoot,
  writeJoinFixture,
  PLAY_WITH_INSTALL_ID,
  writePlayWithFixture,
  WINDOWS_BUILD_INSTALL_NAME,
  windowsBuildInstallRoot,
  windowsBuildExecutablePath,
  windowsBuildNativeExecutablePath,
  writeWindowsBuildFixture,
  writeWineStub,
  writeUmuStub,
  steamLibraryInstallRoot,
  writeSteamLibraryFixture,
  steamStubLogPath,
  writeSteamStub,
} from './fixture/installations.mjs'
export { writeControlsSeedFixture } from './fixture/controls.mjs'
export {
  DOWNLOADS_SETTINGS_SEED,
  DOWNLOADS_CACHE_ARCHIVE_ONE,
  DOWNLOADS_CACHE_ARCHIVE_TWO,
  DOWNLOADS_CACHE_TOTAL_BYTES,
  DOWNLOADS_CACHE_ITEM_COUNT,
} from './fixture/downloads.mjs'
export {
  SERVERS_DISABLED_SOURCES,
  SERVERS_MANUAL_SERVER_ADDRESS,
  SERVERS_SCAN_SETTINGS_SEED,
  writeServersListEmptyFixture,
  writeServersListFixture,
  writeServersListErrorFixture,
  writeServersLanFixture,
} from './fixture/servers.mjs'
export { writePopulatedFixture, writeEmptyFixture } from './fixture/populated.mjs'
export {
  REPLAYS_FIXTURE_EXTRA_GAME_DIR,
  REPLAYS_FIXTURE_DEMOS,
  REPLAYS_FIXTURE_DECOYS,
  REPLAYS_FIXTURE_SCANNED_TOTAL,
  replaysExtraFolderFixturePath,
  replaysZipPackArchivePath,
  writeReplaysZipPackArchive,
  removeReplaysZipPackArchive,
  REPLAYS_ROWS_TDM_DEMO,
  REPLAYS_ROWS_DUEL_DEMO,
  REPLAYS_ROWS_MVD_DEMO,
  REPLAYS_ROWS_BROKEN_DEMO,
  REPLAYS_ROWS_UNREADABLE_DEMO,
  REPLAYS_ROWS_ZIP_ARCHIVE,
  REPLAYS_ROWS_ZIP_ENTRY_NAME,
  replaysRowsSidecarPath,
  writeReplaysRowsFixture,
  REPLAYS_SORT_ORDER_VARIANT,
  REPLAYS_SORT_ORDER_FAV_NEWER_DEMO,
  REPLAYS_SORT_ORDER_FAV_OLDER_DEMO,
  REPLAYS_SORT_ORDER_NONFAV_NEWEST_DEMO,
  REPLAYS_SORT_ORDER_NONFAV_OLDEST_DEMO,
  REPLAYS_SORT_ORDER_FAV_NEWER_SIDECAR_MAP,
  REPLAYS_SORT_ORDER_FAV_OLDER_SIDECAR_MAP,
  REPLAYS_SORT_ORDER_NONFAV_NEWEST_SIDECAR_MAP,
  REPLAYS_SORT_ORDER_NONFAV_OLDEST_SIDECAR_MAP,
  writeReplaysSortOrderFixture,
  REPLAYS_TEAMS_VARIANT,
  REPLAYS_TEAMS_EXAMPLE_DEMO,
  REPLAYS_TEAMS_HEADER_DEMO,
  REPLAYS_TEAMS_SIDECAR_DEMO,
  writeReplaysTeamsFixture,
  REPLAYS_FILTER_VARIANT,
  replaysFilterFixturePath,
  REPLAYS_FILTER_FAVOURITE_DEMO,
  REPLAYS_FILTER_NONFAV_DEMO,
  REPLAYS_FILTER_HEADERONLY_DEMO,
  REPLAYS_FILTER_NAMEFACT_DEMO,
  REPLAYS_FILTER_SIDECAR_NAME,
  REPLAYS_FILTER_DESCRIPTION_WORD,
  REPLAYS_FILTER_SIDECAR_PLAYER,
  REPLAYS_FILTER_HEADER_PLAYER,
  REPLAYS_FILTER_NAMEFACT_PLAYER,
  REPLAYS_FILTER_SHARED_MAP,
  REPLAYS_FILTER_NONFAV_MAP,
  REPLAYS_FILTER_FAVOURITE_TAG,
  REPLAYS_FILTER_LAN_TAG,
  REPLAYS_FILTER_FUN_TAG,
  REPLAYS_FILTER_MOD_OPTIONS,
  REPLAYS_FILTER_GAMEMODE_OPTIONS,
  REPLAYS_FILTER_HEADERONLY_MAP,
  REPLAYS_FILTER_MAP_OPTIONS,
  writeReplaysFilterFixture,
  removeReplaysFilterFixture,
  REPLAYS_FOLDERS_VARIANT,
  replaysFoldersFixturePath,
  REPLAYS_FOLDERS_ROOT_DEMO,
  REPLAYS_FOLDERS_A_DEMO,
  REPLAYS_FOLDERS_C_DEMO,
  REPLAYS_FOLDERS_ZIP,
  REPLAYS_FOLDERS_ZIP_ENTRIES,
  writeReplaysFoldersFixture,
  removeReplaysFoldersFixture,
  REPLAYS_DATE_FILTER_VARIANT,
  replaysDateFilterFixturePath,
  REPLAYS_DATE_FILTER_TODAY_DEMO,
  REPLAYS_DATE_FILTER_RECENT_DEMO,
  REPLAYS_DATE_FILTER_OLD_DEMO,
  REPLAYS_DATE_FILTER_VERYOLD_DEMO,
  REPLAYS_DATE_FILTER_RECENT_MOD,
  writeReplaysDateFilterFixture,
  removeReplaysDateFilterFixture,
  REPLAYS_SCALE_FILE_COUNT,
  REPLAYS_SCALE_LAST_FILE_NAME,
  writeReplaysScaleFixture,
  REPLAYS_FOLDER_SCALE_VARIANT,
  REPLAYS_FOLDER_SCALE_LEVEL_SIZES,
  REPLAYS_FOLDER_SCALE_FOLDER_COUNT,
  REPLAYS_FOLDER_SCALE_DEMO_COUNT,
  REPLAYS_FOLDER_SCALE_ROOT_CHILDREN,
  REPLAYS_FOLDER_SCALE_ROOT_LABEL,
  REPLAYS_FOLDER_SCALE_OPEN_FOLDER,
  writeReplaysFolderScaleFixture,
  writeReplaysListLoadingFixture,
  replaysListErrorMissingFolderPath,
  replaysListErrorBrokenArchiveFolderPath,
  REPLAYS_LIST_ERROR_BROKEN_ARCHIVE_NAME,
  writeReplaysListErrorFixture,
  writeReplaysScopeNoneSelectedFixture,
} from './fixture/replays.mjs'
export {
  bootstrapProgramFilesProbePath,
  bootstrapTargetDir,
  BOOTSTRAP_TARGET_LOOSE_FILE,
  bootstrapR1q2TargetDir,
  writeBootstrapR1q2TargetDir,
  vendoredExtractorExists,
  vendoredWindowsExtractorExists,
  R1Q2_FIXTURE_ENGINE_ID,
  BOOTSTRAP_R1Q2_ENGINE_FIXTURE_LAYOUT,
  BOOTSTRAP_R1Q2_DEDICATED_EXE_NAME,
  BOOTSTRAP_ENGINE_FIXTURE_ID,
  BOOTSTRAP_ENGINE_FIXTURE_VERSION,
  BOOTSTRAP_FIXTURE_LAYOUT,
  writeBootstrapTargetDir,
  bootstrapFailureRetryTargetDir,
  resetBootstrapFailureRetryTargetDir,
  startBootstrapFixtureServer,
  RETAIL_PAK_SIZES,
  bootstrapRetailTargetDir,
  writeBootstrapRetailTargetDir,
  bootstrapExistingFolderTargetDir,
  writeBootstrapExistingFolderTargetDir,
  writeBootstrapStoreSources,
  bootstrapExistingFolderSourceDir,
  writeBootstrapExistingFolderSource,
  writeBootstrapExistingFolderUnusableSource,
  bootstrapSubfolderDirs,
  writeBootstrapSubfolderDirs,
} from './fixture/bootstrap.mjs'
export {
  REPLAYS_PLAY_Q2PRO_ID,
  REPLAYS_PLAY_R1Q2_ID,
  REPLAYS_PLAY_BASE_DEMO,
  REPLAYS_PLAY_CTF_DEMO,
  REPLAYS_PLAY_MISSING_MOD_DEMO,
  REPLAYS_PLAY_MISSING_MOD,
  replaysPlayInstallRoot,
  REPLAYS_PLAY_DEMO_MS,
  REPLAYS_PLAY_BROKEN_ID,
  REPLAYS_PLAY_BROKEN_NAME,
  writeReplaysPlayFixture,
  REPLAYS_TIMELINE_VARIANT,
  replaysTimelineEngineFiles,
  replaysStageFollowEngineFiles,
  writeReplaysTimelineFixture,
  REPLAYS_COMMENTS_ZIP,
  REPLAYS_COMMENTS_ZIP_ENTRY,
  writeReplaysCommentsArchiveFixture,
  REPLAYS_PLAY_MVD2_DEMO,
  REPLAYS_PLAY_MVD2_GZ_DEMO,
  REPLAYS_PLAY_MVD2_GAME_DIR,
  writeReplaysPlayMvd2Fixture,
  REPLAYS_COPY_IN_INPLACE_DEMO,
  REPLAYS_COPY_IN_EXTRA_DEMO,
  REPLAYS_COPY_IN_ZIP,
  REPLAYS_COPY_IN_ZIP_ENTRY,
  REPLAYS_COPY_IN_KEEP_DEMO,
  replaysCopyInExtraFolder,
  replaysCopyInDemosDir,
  writeReplaysCopyInFixture,
} from './fixture/replays-play.mjs'
export {
  modsFixtureFiles,
  modsFixtureContentOnlyFiles,
  MODS_INSTALL_R1Q2_ID,
  MODS_INSTALL_R1Q2_NAME,
  MODS_INSTALL_Q2PRO_ID,
  MODS_INSTALL_Q2PRO_NAME,
  writeModsInstallFixture,
  writeReplaysModInstallFixture,
  REPLAYS_MOD_INSTALL_VARIANT,
  INSTALL_MODS_REMOVE_ID,
  INSTALL_MODS_REMOVE_NAME,
  modsRemoveFiles,
  MODS_REMOVE_EDITED_CFG,
  MODS_REMOVE_DEMO_PATH,
  writeModsRemoveFixture,
  INSTALL_MODS_UPDATE_ID,
  INSTALL_MODS_UPDATE_NAME,
  MODS_UPDATE_USER_FILE,
  MODS_UPDATE_USER_BYTES,
  modsUpdateOldFiles,
  modsUpdateNewOpentdmFiles,
  modsUpdateNewActionFiles,
  modsUpdateManualFiles,
  writeModsUpdateFixture,
  writeManualGamedirFile,
  modsCatalogFixtureEntries,
  startModsCatalogFixtureServer,
  startNoEngineForPlatformFixtureServer,
  readTargetTree,
} from './fixture/mods.mjs'

import { writeImportFilesFixture } from './fixture/installations.mjs'
import { writePopulatedFixture, writeEmptyFixture } from './fixture/populated.mjs'
import { writeControlsSeedFixture } from './fixture/controls.mjs'
import {
  writeNewsStaleFixture,
  writeNewsImagesFixture,
  writeNewsCoverFixture,
} from './fixture/news.mjs'
import {
  writeServersScanFixture,
  writeServersListEmptyFixture,
  writeServersListFixture,
  writeServersListErrorFixture,
  writeServersLanFixture,
} from './fixture/servers.mjs'
import {
  REPLAYS_SORT_ORDER_VARIANT,
  REPLAYS_TEAMS_VARIANT,
  REPLAYS_DATE_FILTER_VARIANT,
  writeReplaysRowsFixture,
  writeReplaysScaleFixture,
  REPLAYS_FOLDER_SCALE_VARIANT,
  writeReplaysFolderScaleFixture,
  writeReplaysSortOrderFixture,
  writeReplaysTeamsFixture,
  writeReplaysDateFilterFixture,
  writeReplaysListLoadingFixture,
  writeReplaysListErrorFixture,
  writeReplaysScopeNoneSelectedFixture,
} from './fixture/replays.mjs'
import {
  REPLAYS_TIMELINE_VARIANT,
  writeReplaysPlayFixture,
  writeReplaysTimelineFixture,
} from './fixture/replays-play.mjs'
import { writeReplaysModInstallFixture } from './fixture/mods.mjs'
export { writeEngineChoiceFixture } from './fixture/engine-choice.mjs'
import { writeEngineChoiceFixture } from './fixture/engine-choice.mjs'

/** Every variant name -> its writer; key order is the `ui:seed` order. Variants without a screen
 * of their own (only a flow) are listed too: `ui:verify` reseeds only the variants its screens
 * name, `ui:seed` writes all of them. */
export const VARIANTS = {
  populated: writePopulatedFixture,
  empty: writeEmptyFixture,
  'controls-seed': writeControlsSeedFixture,
  'news-stale': writeNewsStaleFixture,
  'news-images': writeNewsImagesFixture,
  'news-cover': writeNewsCoverFixture,
  'servers-scan': writeServersScanFixture,
  'servers-list-empty': writeServersListEmptyFixture,
  'servers-list': writeServersListFixture,
  'servers-list-error': writeServersListErrorFixture,
  'servers-lan': writeServersLanFixture,
  'replays-rows': writeReplaysRowsFixture,
  'replays-scale': writeReplaysScaleFixture,
  [REPLAYS_FOLDER_SCALE_VARIANT]: writeReplaysFolderScaleFixture,
  'replays-play': writeReplaysPlayFixture,
  [REPLAYS_TIMELINE_VARIANT]: writeReplaysTimelineFixture,
  'replays-mod-install': writeReplaysModInstallFixture,
  [REPLAYS_SORT_ORDER_VARIANT]: writeReplaysSortOrderFixture,
  [REPLAYS_TEAMS_VARIANT]: writeReplaysTeamsFixture,
  [REPLAYS_DATE_FILTER_VARIANT]: writeReplaysDateFilterFixture,
  'replays-list-loading': writeReplaysListLoadingFixture,
  'replays-list-error': writeReplaysListErrorFixture,
  'replays-scope-none-selected': writeReplaysScopeNoneSelectedFixture,
  'engine-choice': writeEngineChoiceFixture,
}

export function writeFixture(variant) {
  // Staged on every reseed regardless of variant: the `empty` variant points at the same three
  // import files as `populated`.
  writeImportFilesFixture()
  if (!Object.hasOwn(VARIANTS, variant)) throw new Error(`unknown fixture variant: ${variant}`)
  return VARIANTS[variant]()
}

export const FIXTURE_VARIANTS = Object.keys(VARIANTS)

/** Variants whose state.json is built on the empty/populated document and so carries
 * `LEGACY_SEED_SCHEMA_VERSION`; every variant except `controls-seed`. */
export const LEGACY_SEED_VARIANTS = FIXTURE_VARIANTS.filter((v) => v !== 'controls-seed')
