import { existsSync, readFileSync, statSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import sharp from 'sharp'
import { MAX_IMAGE_BYTES, MAX_IMAGE_DIMENSION_PX } from '../images/fetch-image'
import { NEWS_TEMPLATES } from './feed-cache'
import { resolveFeed } from './feed-pipeline'

/**
 * Story 095 D4: proves the copy-and-fill kit at
 * `content/q2_community_content/news/_templates/<template>/` exists for every template the
 * launcher's own contract knows about, that each `template.md` is real, parseable frontmatter
 * that survives the real pipeline as its own declared template (not falling back to `text`), and
 * that each image template's `README.md` actually states the rules a contributor needs (formats,
 * size caps, recommended source size, and - for `cover` - its safe zone).
 *
 * Mirrors `news-fixture-contract.test.ts` for resolving the repo root from `__dirname` and reading
 * real files off disk from a vitest test; this file lives at the same depth
 * (`src/main/modules/home/news/`) so it needs the same number of `..` segments.
 *
 * Story 095 D5 adds two more assertions on top of D4's: that the kit overview
 * (`news/_templates/README.md`) links every template's folder, and that the top-level
 * `content/q2_community_content/README.md` mentions every template and carries no "three
 * templates" (or equivalent) claim now that a fourth template (`cover`) exists.
 *
 * Story 095 D6 adds the example images themselves: `example.png` under every image template's
 * folder, generated by `scripts/generate-news-images.mjs`, and asserted here to be a real,
 * in-budget PNG at the size its own README recommends. `text` has no image field, so it gets no
 * example and is asserted to have none.
 */

const REPO_ROOT = join(__dirname, '..', '..', '..', '..', '..')
const TEMPLATES_DIR = join(REPO_ROOT, 'content', 'q2_community_content', 'news', '_templates')

/** Templates whose slide is built around an image, per `feed-pipeline.ts`'s `TEMPLATES_REQUIRING_IMAGE`
 * plus `banner` (image-optional, but still an image template for documentation purposes). `text` is
 * the one template with no `image` field at all. */
const IMAGE_TEMPLATES = ['split', 'banner', 'cover'] as const

function templateDir(template: string): string {
  return join(TEMPLATES_DIR, template)
}

function readTemplateMd(template: string): string {
  return readFileSync(join(templateDir(template), 'template.md'), 'utf-8')
}

function readReadme(template: string): string {
  return readFileSync(join(templateDir(template), 'README.md'), 'utf-8')
}

/** Pulls the "recommended source size" WxH out of a README, e.g. "900×900 px" -> { width: 900, height: 900 }. */
function recommendedSize(readme: string): { width: number; height: number } {
  const match = readme.match(/recommended source size[^\n]*?(\d+)\s*×\s*(\d+)\s*px/i)
  if (!match) throw new Error('expected a "recommended source size: WxH px" line in the README')
  return { width: Number(match[1]), height: Number(match[2]) }
}

const CONTENT_ROOT = join(REPO_ROOT, 'content', 'q2_community_content')

describe('news template kit (content/q2_community_content/news/_templates/)', () => {
  it('every NEWS_TEMPLATES value has a kit folder with template.md and README.md', () => {
    expect(NEWS_TEMPLATES.length).toBeGreaterThan(0)
    for (const template of NEWS_TEMPLATES) {
      const dir = templateDir(template)
      expect(existsSync(dir), `expected a kit folder at ${dir}`).toBe(true)
      expect(existsSync(join(dir, 'template.md')), `expected template.md for ${template}`).toBe(true)
      expect(existsSync(join(dir, 'README.md')), `expected README.md for ${template}`).toBe(true)
    }
  })

  it('each template.md resolves through the real pipeline as its own declared template', () => {
    for (const template of NEWS_TEMPLATES) {
      const text = readTemplateMd(template)
      const result = resolveFeed({
        index: {
          schemaVersion: 1,
          entries: [{ id: `kit-${template}`, file: 'template.md' }],
        },
        documents: { 'template.md': text },
      })

      expect(result.slides, `${template}: expected the kit skeleton to survive resolveFeed()`).toHaveLength(1)
      expect(
        result.slides[0].template,
        `${template}: expected the kit skeleton to resolve as its own template, not fall back`,
      ).toBe(template)
    }
  })

  it('each image template README names the accepted formats, both size caps and the recommended size', () => {
    for (const template of IMAGE_TEMPLATES) {
      const readme = readReadme(template)
      expect(readme, `${template} README: accepted formats`).toMatch(/png/i)
      expect(readme, `${template} README: accepted formats`).toMatch(/jpeg/i)
      expect(readme, `${template} README: accepted formats`).toMatch(/webp/i)
      expect(readme, `${template} README: max file size`).toMatch(/5\s*MB/i)
      expect(readme, `${template} README: max pixel dimension`).toMatch(/4000\s*px/i)
      expect(readme, `${template} README: recommended source size`).toMatch(/recommended source size/i)
    }
  })

  it('the kit overview (_templates/README.md) links every NEWS_TEMPLATES value\'s folder', () => {
    const overview = readFileSync(join(TEMPLATES_DIR, 'README.md'), 'utf-8')
    for (const template of NEWS_TEMPLATES) {
      expect(
        overview,
        `expected _templates/README.md to link ./${template}/`,
      ).toMatch(new RegExp(`\\]\\(\\./${template}/\\)`))
    }
  })

  it('the top-level README mentions every template and makes no "three templates" claim', () => {
    const readme = readFileSync(join(CONTENT_ROOT, 'README.md'), 'utf-8')
    for (const template of NEWS_TEMPLATES) {
      expect(readme, `expected the top-level README to mention \`${template}\``).toMatch(
        new RegExp('`' + template + '`'),
      )
    }
    expect(readme, 'expected no "three templates" style claim').not.toMatch(
      /\bthree\s+templates\b|\bexactly\s+three\b/i,
    )
  })

  it('the top-level README\'s order-list claim matches the real index.json order values', () => {
    const readme = readFileSync(join(CONTENT_ROOT, 'README.md'), 'utf-8')
    const index = JSON.parse(readFileSync(join(CONTENT_ROOT, 'news', 'index.json'), 'utf-8')) as {
      entries: { order: number }[]
    }
    const realOrders = index.entries.map((entry) => entry.order).sort((a, b) => a - b)

    // The README states its order-list example as "this repository uses 10/20/30[/40...]" - pull
    // whatever slash-separated run of numbers follows "uses" so a stale list (missing a real order
    // value, or including one that no longer exists) fails this test instead of silently drifting.
    const match = readme.match(/this repository uses ([\d/]+)/i)
    expect(match, 'expected an "this repository uses N/N/..." order-list statement in the README').not.toBeNull()
    const statedOrders = match![1].split('/').map(Number)
    expect(statedOrders, "README's stated order list must match news/index.json's real order values").toEqual(
      realOrders,
    )
  })

  it('the top-level README does not claim an unknown template is dropped', () => {
    const readme = readFileSync(join(CONTENT_ROOT, 'README.md'), 'utf-8')
    // AC4/feed-pipeline.ts: an unknown template value falls back to `text` and is KEPT. A README
    // that lists "an unknown template" among the reasons an entry is "dropped on its own" (or
    // equivalent wording) contradicts that real fallback behaviour.
    const droppedSentences = readme.match(/[^.]*\bdropped\b[^.]*\./gi) ?? []
    for (const sentence of droppedSentences) {
      // A sentence stating an unknown template is explicitly *not* dropped (the real, correct
      // fallback behaviour) must not trip this - only flag a sentence that actually attributes
      // dropping to an unknown template.
      if (/\bnot\s+dropped\b/i.test(sentence)) continue
      expect(
        sentence,
        `README sentence claims an entry is dropped, but must not attribute this to an unknown template: ${sentence}`,
      ).not.toMatch(/unknown\s*`?\s*template\s*`?/i)
    }
  })

  it('every image template README states a safe zone (which region survives vs. what crops, and at what width)', () => {
    for (const template of IMAGE_TEMPLATES) {
      const readme = readReadme(template)
      expect(readme, `${template} README: safe zone heading/statement`).toMatch(/safe zone/i)
      expect(readme, `${template} README: what gets cropped`).toMatch(/crop/i)
      expect(readme, `${template} README: at which window/slide width`).toMatch(/\d+\s*px/i)
    }
  })

  it("the cover README's safe zone states its right-anchor specifics", () => {
    const readme = readReadme('cover')
    expect(readme).toMatch(/safe zone/i)
    expect(readme).toMatch(/2560.*640|4:1/i)
    expect(readme).toMatch(/right/i)
  })

  it('the text template has no image field and its README says so', () => {
    const templateMd = readTemplateMd('text')
    expect(templateMd).not.toMatch(/^\s*image:/m)
    const readme = readReadme('text')
    expect(readme).toMatch(/no\s+`?image`?\s+field/i)
  })

  it('every template README states that adding a template does not bump schemaVersion', () => {
    for (const template of NEWS_TEMPLATES) {
      const readme = readReadme(template)
      expect(
        readme,
        `${template} README: expected an R1 note that schemaVersion stays 1`,
      ).toMatch(/schemaVersion.*stays.*1|does not bump.*schemaVersion/i)
    }
  })

  it('every image template folder has an example.png, a valid in-budget PNG at its README\'s recommended size', async () => {
    for (const template of IMAGE_TEMPLATES) {
      const path = join(templateDir(template), 'example.png')
      expect(existsSync(path), `expected ${path} to exist`).toBe(true)

      const bytes = statSync(path).size
      expect(bytes, `${template} example.png: expected it within MAX_IMAGE_BYTES`).toBeLessThanOrEqual(
        MAX_IMAGE_BYTES,
      )
      expect(bytes, `${template} example.png: expected it ≤ 25 KB`).toBeLessThanOrEqual(25 * 1024)

      const metadata = await sharp(path).metadata()
      expect(metadata.format, `${template} example.png: expected a PNG`).toBe('png')
      expect(metadata.width, `${template} example.png: width within MAX_IMAGE_DIMENSION_PX`).toBeLessThanOrEqual(
        MAX_IMAGE_DIMENSION_PX,
      )
      expect(metadata.height, `${template} example.png: height within MAX_IMAGE_DIMENSION_PX`).toBeLessThanOrEqual(
        MAX_IMAGE_DIMENSION_PX,
      )

      const expected = recommendedSize(readReadme(template))
      expect(metadata.width, `${template} example.png: width matches README's recommended size`).toBe(
        expected.width,
      )
      expect(metadata.height, `${template} example.png: height matches README's recommended size`).toBe(
        expected.height,
      )
    }
  })

  it('text has no example image', () => {
    expect(existsSync(join(templateDir('text'), 'example.png'))).toBe(false)
  })
})
