import { REPO_ROOT, UI_VERIFY_ROOT, assertInside } from '../paths.mjs'
import { join } from 'node:path'
import {
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  statSync,
  truncateSync,
  writeFileSync,
} from 'node:fs'
import { execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { createServer } from 'node:http'
import { rmDirBestEffort } from './core.mjs'
import { ENGINE_FIXTURE_FILES } from './installations.mjs'
import {
  buildModsInstallPackages,
  buildModsReplaysPackage,
  buildModsUpdatePackages,
  modsInstallManifestEntries,
  modsReplaysManifestEntries,
  modsUpdateManifestEntries,
} from './mods.mjs'

// --- story 074 D8: the offline bootstrap-wizard fixture -----------------------------------------
//
// `scripts/flows/bootstrap-wizard.mjs` runs the REAL bootstrap job - real manifest fetch, three
// real verified downloads, three real `7za.exe` extractions, the real assemble/revalidate passes -
// and must do so with no outbound network access whatsoever. That needs three things, and all
// three are built here:
//
//   1. three real, 7-Zip-extractable archives, laid out the way the REAL archives are - not the
//      way `bootstrap/assemble.ts`'s allowlist was once guessed to expect (story 076 measured and
//      fixed that gap): `q2pro64.exe` + `baseq2/{gamex86_64.dll,q2pro.menu}` for the engine,
//      `Install/Data/baseq2/{pak0.pak,players/...}` for the demo, and
//      `baseq2/{pak1.pak,pak2.pak,players/...}` for the point release - plus `ctf/`, `xatrix/`
//      and `rogue/` payloads inside the point-release archive so AC8's "no ctf/xatrix/rogue
//      directory is created" is a claim about real, discarded input rather than about an input
//      that never had any. `BOOTSTRAP_FIXTURE_LAYOUT` below is this layout as data;
//   2. a `127.0.0.1` server serving both manifest files and those archives - with the real
//      sha256/size of the archives on disk, so nothing about the verification step is faked; and
//   3. a target folder that is deliberately BOTH under a fake `Program Files` root (AC2) and
//      non-empty (AC3), so one pass through the wizard renders and acknowledges both warnings.
//
// Everything lands under `.ui-verify/fixture/bootstrap/` and nowhere else - the paths go through
// `assertInside(UI_VERIFY_ROOT, ...)`, the same containment discipline `harness.mjs` applies to
// `--user-data-dir`.
//
// None of this is part of `writeFixture()`/`ui:seed`: these artefacts are only ever wanted by that
// one flow, they cost a few seconds and ~10 MB to build, and (unlike the `populated`/`empty` state
// documents) they are not byte-identical per run, since a zip stores mtimes. That is harmless
// because every digest below is computed from the bytes that were actually written.

/** `.ui-verify/fixture/bootstrap` - everything this section writes lives under it. */
function bootstrapFixtureRoot() {
  return assertInside(
    UI_VERIFY_ROOT,
    join(UI_VERIFY_ROOT, 'fixture', 'bootstrap'),
    'bootstrap fixture root',
  )
}

/**
 * A path under the machine's REAL `%ProgramFiles%` that is only ever *named*, never created and
 * never written to - the target the flow points the wizard's step 2 at to make AC2's Program Files
 * warning appear, before re-picking the real fixture target below.
 *
 * Story 074's refine expected this to work the other way round ("the e2e flow can exercise the
 * verdict by pointing the child process's `ProgramFiles` at a fixture dir - no production backdoor
 * needed"). On Windows it cannot: `ProgramFiles`, `ProgramFiles(x86)` and `NUMBER_OF_PROCESSORS`
 * are regenerated by the loader for every new process from the process's own bitness, so a value
 * handed to `CreateProcess` in the environment block is simply replaced - measured, not assumed.
 * `bootstrap/target.test.ts` can still inject a fake root, because it calls
 * `computeTargetVerdict(path, { env })` in-process; a child process cannot be lied to this way.
 *
 * Naming a real Program Files path is safe here because `computeTargetVerdict` is a read-only
 * verdict: the folder does not have to exist (`programFiles` is a prefix comparison,
 * `alreadyInstalled`/`entries` are skipped for a non-existent directory) and the only write it
 * attempts is the same throwaway probe marker in the nearest existing ancestor that a real user
 * picking that folder would trigger - which fails harmlessly without elevation. The flow never
 * proceeds past the target step with this path selected, so nothing is ever installed there.
 */
export function bootstrapProgramFilesProbePath() {
  const programFiles = process.env.ProgramFiles ?? 'C:\\Program Files'
  return join(programFiles, 'Q2 Launcher UI Verify Fixture')
}

/** The folder the wizard actually installs into: writable, under `.ui-verify/`, and non-empty (AC3). */
export function bootstrapTargetDir() {
  return join(bootstrapFixtureRoot(), 'target', 'Q2PRO Demo')
}

/**
 * The one pre-existing file that makes the target non-empty (AC3). A name that could plausibly be
 * the user's own, since that warning exists precisely because they may have put something here.
 */
export const BOOTSTRAP_TARGET_LOOSE_FILE = 'user-notes.txt'

/**
 * Story 080 D4: the folder `scripts/flows/bootstrap-r1q2.mjs` installs into - a sibling of
 * `bootstrapTargetDir()`, not that same folder (the two flows must not race over one directory).
 * Program-Files/non-empty target warnings are already proven by the Q2PRO flow (AC2/AC3 there), so
 * this one stays fresh and empty rather than re-proving them.
 */
export function bootstrapR1q2TargetDir() {
  return join(bootstrapFixtureRoot(), 'target', 'R1Q2 Fixture')
}

/** Fresh, empty target folder for the R1Q2 flow - deletes any leftover from a previous run. */
export function writeBootstrapR1q2TargetDir() {
  const target = assertInside(UI_VERIFY_ROOT, bootstrapR1q2TargetDir(), 'bootstrap r1q2 target')
  rmDirBestEffort(target)
  mkdirSync(target, { recursive: true })
  return target
}

/** Where the built archives are served from. */
function bootstrapPackagesDir() {
  return join(bootstrapFixtureRoot(), 'packages')
}

/** Scratch trees the archives are built out of; kept afterwards, so a build is easy to inspect. */
export function bootstrapStagingDir() {
  return join(bootstrapFixtureRoot(), 'staging')
}

/** The vendored extractor - the same binary the app spawns (`7za-path.ts`, its dev branch). */
export function vendoredSevenZaPath() {
  return join(REPO_ROOT, 'resources', 'bin', process.platform === 'win32' ? '7za.exe' : '7zz')
}

/** True when that binary is present; the flow refuses to pretend an extraction happened without it. */
export function vendoredExtractorExists() {
  return existsSync(vendoredSevenZaPath())
}

/** The real, absolute path to this repo's vendored Windows 7-Zip binary - the same file
 * `vendoredExtractorExists()` above checks for, reused here as a real spawnable stand-in. */
export function vendoredWindowsExtractorPath() {
  return join(REPO_ROOT, 'resources', 'bin', '7za.exe')
}

/** True once `npm run fetch:7za` has vendored the real Windows binary. Irrelevant off Windows,
 * where the shell-script stub needs no vendored binary at all - callers only ever consult this
 * on `process.platform === 'win32'`. */
export function vendoredWindowsExtractorExists() {
  return existsSync(vendoredWindowsExtractorPath())
}

/**
 * `pak0.pak`'s fixture size: 8 MiB - deliberately NOT `RETAIL_PAK_SIZES['pak0.pak']`
 * (183,997,730, `src/shared/constants.ts`). `inspectInstallation` tells the demo from the retail
 * game by exactly that comparison, and AC7's Demo marker is derived from the
 * `validation.pak0NotRetail` warning it raises, so a retail-sized fixture would make this flow
 * prove the opposite of what it exists for.
 */
const FIXTURE_PAK0_BYTES = 8 * 1024 * 1024

/** Mirrors `RETAIL_PAK_SIZES['pak2.pak']` (45,055). Nothing depends on it; free realism. */
const FIXTURE_PAK2_BYTES = 45_055

/** `pak1.pak`'s fixture size - distinct from `FIXTURE_PAK2_BYTES` so the two files are never confused on disk. */
const FIXTURE_PAK1_BYTES = 38_912

/**
 * How many files the discarded `ctf/` payload holds. Two jobs: it makes AC8's negative assertion
 * meaningful (a real payload the allowlist walks past), and it gives the job's tail - the final
 * revalidation plus the `rm -r` of the three extract trees, both of which happen AFTER
 * `markPlayable` - enough real work that "Play is enabled while the job is still running" (AC6) is
 * an observable window rather than a coin flip. See the sampler in
 * `scripts/flows/bootstrap-wizard.mjs`.
 *
 * Measured, not guessed: at 300 files the flow's sampler caught that window in ~60ms of samples, at
 * 900 in ~80ms. Most of it turns out to be the two `jobs:changed` round trips and their React
 * renders rather than the disk work, so raising this further buys little - it is kept at 900 for the
 * ~33% margin it does buy, and because the real 3.20 point release ships a `ctf/` payload of
 * comparable size, which makes AC8's negative assertion less artificial rather than more.
 */
const FIXTURE_CTF_FILE_COUNT = 900

/** Deterministic filler, never random, so two builds are comparable. */
export function filler(bytes, byte) {
  return Buffer.alloc(bytes, byte)
}

export function writeFileIn(dir, name, contents) {
  mkdirSync(dir, { recursive: true })
  writeFileSync(join(dir, name), contents)
}

/**
 * Builds one staging tree and zips its named top-level entries into `packages/<fileName>`.
 *
 * A `.zip` rather than a self-extracting `.exe`: the point of this fixture is that the app's REAL
 * extractor runs against a REAL archive, and a hand-forged byte sequence that merely looked like an
 * installer would prove nothing. `7za.exe` is the same binary `extractor.ts` spawns, so an archive
 * it wrote is certainly one the app can read. The entries are named explicitly rather than globbed,
 * so the archive's internal layout is stated here instead of inherited from a directory walk.
 */
export function buildFixturePackage({ fileName, stagingName, entries, build }) {
  const staging = join(bootstrapStagingDir(), stagingName)
  rmSync(staging, { recursive: true, force: true })
  mkdirSync(staging, { recursive: true })
  build(staging)

  const archivePath = join(bootstrapPackagesDir(), fileName)
  mkdirSync(bootstrapPackagesDir(), { recursive: true })
  // `7za a` APPENDS to an existing archive, so a stale one has to go first.
  rmSync(archivePath, { force: true })
  execFileSync(
    vendoredSevenZaPath(),
    ['a', '-tzip', '-mx1', '-bso0', '-bse0', '-bd', archivePath, ...entries],
    { cwd: staging, windowsHide: true },
  )

  const bytes = readFileSync(archivePath)
  return {
    fileName,
    path: archivePath,
    sizeBytes: bytes.byteLength,
    sha256: createHash('sha256').update(bytes).digest('hex'),
  }
}

/**
 * The three archives, in the order the job downloads them. Package ids satisfy `job.ts`'s
 * `SAFE_PATH_SEGMENT` (an id becomes an extract-directory name) and the file names satisfy
 * `paths.ts`'s `isSafeDownloadFileName` (a name becomes a cache file name) - both are refused
 * rather than sanitised, so a fixture that ignored either would fail before a byte moved.
 *
 * `wrapperNestedLayout` (story 078 D9): every package's payload moves one wrapper level deeper
 * than any candidate `assemble.ts`'s allowlist (`buildFixedEntries()`) accepts - real enough that
 * the extractor and the allowlist search genuinely run over it, not a simulated failure. See
 * `scripts/flows/bootstrap-failure.mjs`'s own header comment for exactly what this variant proves
 * and the one thing it deliberately cannot prove (a real `installationNotPlayable` failure).
 */
/** Story 080 D4: the r1q2 fixture engine package's id/version - a distinct id from the q2pro one
 * (`'q2pro-fixture-client'`), so a manifest/server can tell the two engine packages apart. Exported
 * so `scripts/flows/bootstrap-r1q2.mjs` can pass it straight to `failPrimaryOnlyFor` rather than
 * duplicating the literal. */
export const R1Q2_FIXTURE_ENGINE_ID = 'r1q2-fixture-client'

const R1Q2_FIXTURE_ENGINE_VERSION = 'r1q2-fixture-1'

/**
 * Every source-relative path `buildR1q2EnginePackage()` writes that the real allowlist
 * (`buildR1q2EngineEntries()`, `bootstrap/assemble.ts`) is expected to find - mirrors
 * `BOOTSTRAP_FIXTURE_LAYOUT`'s style, but only the engine role: demo/point-release are unchanged
 * and engine-independent, so they stay documented once, above.
 */
export const BOOTSTRAP_R1Q2_ENGINE_FIXTURE_LAYOUT = [
  'r1q2.exe',
  'ref_r1gl.dll',
  'baseq2/gamex86.dll',
]

/** The one file the r1q2 fixture archive carries that the allowlist must never assemble (AC3). */
export const BOOTSTRAP_R1Q2_DEDICATED_EXE_NAME = 'dedicated.exe'

/**
 * Story 080 D4: a second, R1Q2-shaped fixture engine package - real enough that the app's real
 * extractor and the real `buildR1q2EngineEntries()` allowlist both run over it, not a simulated
 * stand-in. Ships `dedicated.exe` at the archive root alongside the three required files, exactly
 * like the real pinned package (`docs/requirements/080-*.md`'s measured archive table) - so the
 * flow that consumes this package can assert the allowlist excluded a file that was genuinely
 * there, not one that never existed.
 */
function buildR1q2EnginePackage() {
  const archiveInfo = buildFixturePackage({
    fileName: 'r1q2-fixture-client.zip',
    stagingName: 'r1q2-engine',
    entries: ['r1q2.exe', 'ref_r1gl.dll', 'baseq2', 'dedicated.exe'],
    build: (staging) => {
      writeFileIn(staging, 'r1q2.exe', filler(64 * 1024, 0x52))
      writeFileIn(staging, 'ref_r1gl.dll', filler(32 * 1024, 0x67))
      writeFileIn(join(staging, 'baseq2'), 'gamex86.dll', filler(16 * 1024, 0x67))
      // Excluded by the allowlist on purpose (AC3) - a distinct fill byte from every other file
      // here, so a stray byte-for-byte comparison could never mistake it for one of the required
      // three.
      writeFileIn(staging, 'dedicated.exe', filler(24 * 1024, 0x64))
    },
  })
  return {
    role: 'engine',
    id: R1Q2_FIXTURE_ENGINE_ID,
    version: R1Q2_FIXTURE_ENGINE_VERSION,
    ...archiveInfo,
  }
}

/**
 * Story 092 D8: the Q2PRO fixture engine package's id/version - already a magic literal ("fixture-1")
 * below before this story, now named and exported so `engine-update.mjs` can assert the update job
 * landed on the manifest's own pin (`engine-update-target`) without a second, driftable copy of the
 * string.
 */
export const BOOTSTRAP_ENGINE_FIXTURE_ID = 'q2pro-fixture-client'

export const BOOTSTRAP_ENGINE_FIXTURE_VERSION = 'fixture-1'

function buildBootstrapPackages({
  demoContributesNothing = false,
  wrapperNestedLayout = false,
  includeR1q2 = false,
} = {}) {
  const engine = buildFixturePackage({
    fileName: 'q2pro-fixture-client.zip',
    stagingName: 'engine',
    entries: wrapperNestedLayout ? ['Install'] : ['q2pro64.exe', 'baseq2'],
    build: (staging) => {
      // `wrapperNestedLayout`: everything the healthy build writes at the archive root or under a
      // plain `baseq2/` instead lands under `Install/Data/` - `assemble.ts`'s engine candidates
      // (`['q2pro.exe', 'q2pro64.exe']` at the root, `baseq2/gamex86_64.dll`) have no `Install/
      // Data/` fallback at all, so this package genuinely stops contributing anything, the same as
      // the demo/point-release packages below.
      const root = wrapperNestedLayout ? join(staging, 'Install', 'Data') : staging
      // At the archive root, matching both the pinned Q2PRO release zip's own layout - which
      // calls its binary `q2pro64.exe`, not `q2pro.exe` - and `assemble.ts`'s
      // `{ from: ['q2pro.exe', 'q2pro64.exe'] }` allowlist entry (story 076 D1).
      // Story 092 D8: sizes/fill bytes come from `ENGINE_FIXTURE_FILES` (declared above,
      // module-level, already initialised by the time this build function actually runs - see that
      // constant's own doc comment) rather than repeating the literals here, so `engine-update.mjs`'s
      // on-disk byte assertions can never drift from what this archive actually contains.
      writeFileIn(
        root,
        'q2pro64.exe',
        filler(
          ENGINE_FIXTURE_FILES['q2pro64.exe'].sizeBytes,
          ENGINE_FIXTURE_FILES['q2pro64.exe'].fillByte,
        ),
      )
      // Not allowlisted, on purpose: the real engine build does ship a `baseq2/` of its own (game
      // DLLs), and AC8's guarantee has to hold for that too.
      writeFileIn(
        join(root, 'baseq2'),
        'gamex86_64.dll',
        filler(
          ENGINE_FIXTURE_FILES['baseq2/gamex86_64.dll'].sizeBytes,
          ENGINE_FIXTURE_FILES['baseq2/gamex86_64.dll'].fillByte,
        ),
      )
      // Ships alongside the binary and DLL in the same package (story 076 D1's allowlist, marked
      // optional). A few hundred bytes is enough - only its presence is ever checked.
      writeFileIn(
        join(root, 'baseq2'),
        'q2pro.menu',
        filler(
          ENGINE_FIXTURE_FILES['baseq2/q2pro.menu'].sizeBytes,
          ENGINE_FIXTURE_FILES['baseq2/q2pro.menu'].fillByte,
        ),
      )
    },
  })

  const demo = buildFixturePackage({
    fileName: 'q2-demo-fixture.zip',
    stagingName: 'demo',
    entries: ['Install'],
    build: (staging) => {
      // Nested under `Install/Data/` - the real id Software InstallShield demo installer's actual
      // layout (measured 2026-09-08, story 076's Requirement table), not the flat `baseq2/` the
      // fixture used to guess. No `video/` anywhere in this package: the real archive has none
      // (AC4 - an absent `video/` is a normal outcome, never an error).
      //
      // `wrapperNestedLayout` (story 078 D9) nests one level deeper still, under `Install/Data/
      // Setup/` - `assemble.ts`'s demo candidate list already accepts plain `Install/Data/baseq2/
      // pak0.pak` as a fallback (story 076 D1), so matching that exact shape would leave this
      // package healthy rather than broken. `demoContributesNothing` (story 076 D6) is a
      // different, narrower brokenness (the required file withheld outright, not moved) and stays
      // independent of this option - both default off, so neither changes the other's behaviour.
      const baseq2 = wrapperNestedLayout
        ? join(staging, 'Install', 'Data', 'Setup', 'baseq2')
        : join(staging, 'Install', 'Data', 'baseq2')
      if (!demoContributesNothing) {
        writeFileIn(baseq2, 'pak0.pak', filler(FIXTURE_PAK0_BYTES, 0x50))
      }
      writeFileIn(join(baseq2, 'players', 'male'), 'tris.md2', filler(4 * 1024, 0x54))
    },
  })

  const pointRelease = buildFixturePackage({
    fileName: 'q2-point-release-fixture.zip',
    stagingName: 'point-release',
    // The `ctf`/`xatrix`/`rogue` discard payload (AC8's negative assertion, and the file count
    // that gives `bootstrap-wizard.mjs`'s AC6 sampler something to catch) is dropped entirely for
    // `wrapperNestedLayout`: this variant's flow never asserts either of those, and the discard
    // payload's only other job - slowing the run down enough for a mid-job sample - is not needed
    // for a run this flow expects to fail, not catch mid-flight.
    entries: wrapperNestedLayout ? ['Install'] : ['baseq2', 'ctf', 'xatrix', 'rogue'],
    build: (staging) => {
      if (wrapperNestedLayout) {
        // Nested under `Install/Data/`, same wrapper as the demo package above. Unlike demo's
        // `baseq2/pak0.pak`, `assemble.ts` has no `Install/Data/` fallback candidate at all for
        // `baseq2/pak1.pak`/`baseq2/pak2.pak` (story 076 D1's Requirement table only measured the
        // demo installer nesting its payload, not the point-release one) - so this single wrapper
        // level is already enough to break it, no extra nesting needed.
        const baseq2 = join(staging, 'Install', 'Data', 'baseq2')
        writeFileIn(baseq2, 'pak1.pak', filler(FIXTURE_PAK1_BYTES, 0x51))
        writeFileIn(baseq2, 'pak2.pak', filler(FIXTURE_PAK2_BYTES, 0x52))
        writeFileIn(join(baseq2, 'players', 'male'), 'tris.md2', filler(4 * 1024, 0x54))
        return
      }
      writeFileIn(join(staging, 'baseq2'), 'pak1.pak', filler(FIXTURE_PAK1_BYTES, 0x51))
      writeFileIn(join(staging, 'baseq2'), 'pak2.pak', filler(FIXTURE_PAK2_BYTES, 0x52))
      // The real 3.20 full/CTF package ships `baseq2/players/` directly under its own `baseq2/`
      // - not nested under `Install/Data/` like the demo above.
      writeFileIn(join(staging, 'baseq2', 'players', 'male'), 'tris.md2', filler(4 * 1024, 0x54))
      for (let index = 0; index < FIXTURE_CTF_FILE_COUNT; index += 1) {
        writeFileIn(join(staging, 'ctf'), `ctf-payload-${index}.dat`, filler(4 * 1024, 0x43))
      }
      writeFileIn(join(staging, 'xatrix'), 'pak0.pak', filler(8 * 1024, 0x58))
      writeFileIn(join(staging, 'rogue'), 'pak0.pak', filler(8 * 1024, 0x47))
    },
  })

  const result = [
    {
      role: 'engine',
      id: BOOTSTRAP_ENGINE_FIXTURE_ID,
      version: BOOTSTRAP_ENGINE_FIXTURE_VERSION,
      ...engine,
    },
    { role: 'demo', id: 'q2-demo-fixture', version: '3.14-fixture', ...demo },
    {
      role: 'point-release',
      id: 'q2-point-release-fixture',
      version: '3.20-fixture',
      ...pointRelease,
    },
  ]
  // Story 080 D4: additive, defaulted off - every existing caller keeps getting exactly the three
  // entries above, in the same order, with the same fields.
  if (includeR1q2) result.push(buildR1q2EnginePackage())
  return result
}

/**
 * Every source-relative path `buildBootstrapPackages()` actually writes, by role - literal, not
 * computed, so a later deliverable (076 D5) can cross-check it against a real-archive listing and
 * against `assemble.ts`'s allowlist candidates without re-deriving it. Deliberately excludes the
 * `ctf`/`xatrix`/`rogue` discard payloads: this documents what the ALLOWLIST is expected to find,
 * not everything the archive contains.
 */
export const BOOTSTRAP_FIXTURE_LAYOUT = {
  engine: ['q2pro64.exe', 'baseq2/gamex86_64.dll', 'baseq2/q2pro.menu'],
  demo: ['Install/Data/baseq2/pak0.pak', 'Install/Data/baseq2/players/male/tris.md2'],
  'point-release': ['baseq2/pak1.pak', 'baseq2/pak2.pak', 'baseq2/players/male/tris.md2'],
}

/**
 * Creates the target folder fresh, holding exactly one loose file. Called on every run, which is
 * what makes the flow re-runnable: a previous run left a whole assembled installation in there.
 */
export function writeBootstrapTargetDir() {
  const target = assertInside(UI_VERIFY_ROOT, bootstrapTargetDir(), 'bootstrap target')
  rmDirBestEffort(target)
  mkdirSync(target, { recursive: true })
  writeFileSync(
    join(target, BOOTSTRAP_TARGET_LOOSE_FILE),
    'A file of the user that was already sitting in this folder.\n',
    'utf8',
  )
  return target
}

/**
 * Story 077 D5: the target `scripts/flows/bootstrap-failure-retry.mjs`'s OWN wizard-created
 * installation uses - a sibling of `bootstrapTargetDir()` above, not that same folder. That one is
 * deliberately pre-seeded non-empty (AC3's warning, story 074); this one has to be genuinely FRESH -
 * the story's own "Decided during refine" note is explicit that the failing-then-succeeding run
 * happens against an installation the flow creates itself, distinct from the pre-seeded fixture row
 * `populatedInstallations()` adds for AC1's restart proof.
 */
export function bootstrapFailureRetryTargetDir() {
  return join(bootstrapFixtureRoot(), 'target', 'Failure Retry Demo')
}

/**
 * Deletes any leftover from a previous run and returns the (non-existent) path - what makes the
 * flow re-runnable without a manual reseed: a previous run's second (succeeding) wizard pass would
 * otherwise leave a fully assembled installation sitting where the next run needs a fresh folder.
 * Unlike `writeBootstrapTargetDir()`, this never recreates the directory or seeds a loose file in
 * it - the wizard's own `create()` step is what brings it into being, on the flow's first run.
 */
export function resetBootstrapFailureRetryTargetDir() {
  const target = assertInside(
    UI_VERIFY_ROOT,
    bootstrapFailureRetryTargetDir(),
    'bootstrap failure-retry target',
  )
  rmDirBestEffort(target)
  return target
}

/** How many body chunks each archive response is split into, and the pause between them. */
const BOOTSTRAP_SERVE_CHUNKS = 10

const BOOTSTRAP_SERVE_CHUNK_DELAY_MS = 45

/**
 * Starts the loopback fixture server and returns `{ baseUrl, packages, totalSizeBytes, close }`.
 *
 * **Bound to `127.0.0.1` explicitly, on an OS-assigned port.** The address is not decoration: the
 * app's harness override (`src/main/services/content/source.ts`) refuses any base URL whose
 * hostname is not literally `127.0.0.1`, and so does the harness-only package-URL schema
 * (`harnessLoopbackUrlSchema`) - a fixture server on any other interface could not be reached even
 * with both gates open.
 *
 * Archive bodies are streamed in `BOOTSTRAP_SERVE_CHUNKS` chunks with a small pause between them.
 * That is not throttling for its own sake: on loopback these archives transfer in single-digit
 * milliseconds, and the flow needs the download phase to last long enough to activate the freshly
 * registered installation before the job reaches its playable moment (AC6). `content-length` is
 * still the real, full size, so `fetcher.ts`'s size pre-check and its 30s stall detector both see
 * exactly what they would see from a real mirror.
 *
 * Only the paths registered below exist; everything else answers 404, so a request the app should
 * never make shows up as a failure rather than as silence.
 *
 * `demoContributesNothing` (story 076 D6) forwards straight into `buildBootstrapPackages()` - see
 * its own doc comment. Defaulted off, so every existing caller keeps working unchanged.
 *
 * `failFirstAttemptFor` (story 077 D5): a package id (`buildBootstrapPackages()`'s own `id`, e.g.
 * `'q2pro-fixture-client'`) whose PRIMARY url and MIRROR url each 404 on their own first request,
 * then serve that same package normally on every request after. This has to be a property of the
 * *server*, not of the flow driving it: `Q2L_UI_CONTENT_REPO_BASE` is fixed for the whole app
 * session (`src/main/lib/ui-harness.ts` reads it once), so a single flow that wants to prove both
 * the failing first run (AC1/AC5) and the adopting, succeeding retry (AC4/AC7) in one app session
 * has no other way to make the second attempt succeed where the first did not (Decisions (Refine)).
 * Undefined/omitted changes nothing about how every existing caller behaves.
 *
 * `wrapperNestedLayout` (story 078 D9) forwards straight into `buildBootstrapPackages()` too - see
 * its own doc comment and `scripts/flows/bootstrap-failure.mjs`. Defaulted off, like the two above.
 *
 * `includeR1q2` (story 080 D4) forwards into `buildBootstrapPackages()` and, when true, also makes
 * `/engines/manifest.json` list a second `kind:'engine', engine:'r1q2'` package and pin it
 * (`pinned.r1q2`) alongside q2pro's. Defaulted off - a server started without it emits byte-identical
 * output to every caller that predates this option.
 *
 * `failPrimaryOnlyFor` (story 080 D4, AC2): a package id, or an array of ids, whose PRIMARY url
 * (`/packages/<file>`) 404s on EVERY request, forever, while its MIRROR url (`/mirror/<file>`) serves
 * normally from the very first request. Unlike `failFirstAttemptFor` above (which models a whole
 * failed job that a retry then adopts), this models a single download attempt whose community/primary
 * transport is down but whose original/mirror URL works - the literal AC2 wording. Independent of
 * `failFirstAttemptFor`: both can be given for *different* package ids without either silently
 * disabling the other; combining them for the SAME id is not a supported/needed combination.
 *
 * `bleedingEdgeVersion` (story 092 D8): when given, registers `/packages/version.txt` - a plain-text
 * body of this string - alongside the Q2PRO engine package's own `/packages/<fileName>` route.
 * `probeBleedingEdge()` (`src/main/modules/downloads/engine/bleeding-edge.ts`) derives its
 * `version.txt` request by swapping the pinned package's asset URL's own final path segment, which
 * for this server is always `/packages/<engine fileName>` - so the sibling path is always
 * `/packages/version.txt`, regardless of the engine package's own file name. Defaulted off (`undefined`
 * registers no route at all), so every caller that predates this option keeps getting exactly the
 * same 404-everything-else behaviour it always has.
 */
export async function startBootstrapFixtureServer({
  demoContributesNothing = false,
  failFirstAttemptFor,
  wrapperNestedLayout = false,
  includeR1q2 = false,
  failPrimaryOnlyFor,
  bleedingEdgeVersion,
  modsInstall = false,
  modsReplays,
  modsUpdate = false,
} = {}) {
  const packages = buildBootstrapPackages({
    demoContributesNothing,
    wrapperNestedLayout,
    includeR1q2,
  })

  const failFirstPackage = failFirstAttemptFor
    ? packages.find((pkg) => pkg.id === failFirstAttemptFor)
    : undefined
  if (failFirstAttemptFor && !failFirstPackage) {
    throw new Error(
      `startBootstrapFixtureServer: failFirstAttemptFor ${JSON.stringify(failFirstAttemptFor)} ` +
        `matches no package id (have: ${packages.map((pkg) => pkg.id).join(', ')})`,
    )
  }
  /** The primary and mirror request paths that must 404 exactly once. Empty when the option is
   * unused, so nothing about a server started without it changes. */
  const failFirstPaths = failFirstPackage
    ? new Set([`/packages/${failFirstPackage.fileName}`, `/mirror/${failFirstPackage.fileName}`])
    : new Set()
  /** Which of `failFirstPaths` has already 404'd once - so the SECOND request to it (the retry) is
   * served normally. */
  const failedOnce = new Set()

  const failPrimaryIds = new Set(
    failPrimaryOnlyFor === undefined
      ? []
      : Array.isArray(failPrimaryOnlyFor)
        ? failPrimaryOnlyFor
        : [failPrimaryOnlyFor],
  )
  for (const id of failPrimaryIds) {
    if (!packages.some((pkg) => pkg.id === id)) {
      throw new Error(
        `startBootstrapFixtureServer: failPrimaryOnlyFor ${JSON.stringify(id)} matches no package ` +
          `id (have: ${packages.map((pkg) => pkg.id).join(', ')})`,
      )
    }
  }
  /** PRIMARY-only request paths that 404 on every request, forever - never the mirror path. */
  const failPrimaryPaths = new Set(
    packages.filter((pkg) => failPrimaryIds.has(pkg.id)).map((pkg) => `/packages/${pkg.fileName}`),
  )

  /** Everything this server is willing to serve, by request path. */
  const routes = new Map()
  /** Every path that was requested, in order - the flow prints it as its own offline evidence. */
  const requested = []

  const server = createServer((request, response) => {
    const path = (request.url ?? '/').split('?')[0]
    requested.push(path)
    if (failPrimaryPaths.has(path)) {
      response.writeHead(404, { 'content-type': 'text/plain' })
      response.end('not found (failPrimaryOnlyFor - primary permanently down)')
      return
    }
    if (failFirstPaths.has(path) && !failedOnce.has(path)) {
      failedOnce.add(path)
      response.writeHead(404, { 'content-type': 'text/plain' })
      response.end('not found (failFirstAttemptFor - first attempt only)')
      return
    }
    const route = routes.get(path)
    if (!route) {
      response.writeHead(404, { 'content-type': 'text/plain' })
      response.end('not found')
      return
    }
    void route(response)
  })

  await new Promise((resolve, reject) => {
    server.once('error', reject)
    server.listen(0, '127.0.0.1', resolve)
  })

  const { port } = server.address()
  const baseUrl = `http://127.0.0.1:${port}`

  const jsonRoute = (body) => (response) => {
    const bytes = Buffer.from(JSON.stringify(body), 'utf8')
    response.writeHead(200, {
      'content-type': 'application/json',
      'content-length': bytes.byteLength,
    })
    response.end(bytes)
  }

  const archiveRoute =
    (archivePath, corrupt = false, chunkDelayMs = BOOTSTRAP_SERVE_CHUNK_DELAY_MS) =>
    async (response) => {
      const bytes = readFileSync(archivePath)
      // `corrupt`: same length, one flipped byte - the manifest SHA256 no longer matches.
      if (corrupt) bytes[bytes.byteLength - 1] ^= 0xff
      response.writeHead(200, {
        'content-type': 'application/octet-stream',
        'content-length': bytes.byteLength,
      })
      const chunkSize = Math.ceil(bytes.byteLength / BOOTSTRAP_SERVE_CHUNKS)
      for (let offset = 0; offset < bytes.byteLength; offset += chunkSize) {
        response.write(bytes.subarray(offset, Math.min(offset + chunkSize, bytes.byteLength)))
        await new Promise((done) => setTimeout(done, chunkDelayMs))
      }
      response.end()
    }

  const manifestPackage = (pkg, extra) => ({
    ...extra,
    id: pkg.id,
    version: pkg.version,
    sizeBytes: pkg.sizeBytes,
    sha256: pkg.sha256,
    url: `${baseUrl}/packages/${pkg.fileName}`,
    // A non-empty `mirrors` array, so the schema's mirror rule is exercised rather than bypassed.
    // Both entries work; the primary always succeeds here, so the mirror is never actually read.
    mirrors: [`${baseUrl}/mirror/${pkg.fileName}`],
    contents: [{ from: '.', to: extra.kind === 'engine' ? 'root' : 'baseq2' }],
  })

  // `q2pro-fixture-client` is always first in `packages` (see `buildBootstrapPackages()`), so this
  // finds it even when the r1q2 entry below is also present with the same `role`.
  const engine = packages.find((pkg) => pkg.role === 'engine')
  const demo = packages.find((pkg) => pkg.role === 'demo')
  const pointRelease = packages.find((pkg) => pkg.role === 'point-release')
  const r1q2Engine = includeR1q2
    ? packages.find((pkg) => pkg.id === R1Q2_FIXTURE_ENGINE_ID)
    : undefined

  // Mirrors `ENGINES_MANIFEST_PATH`/`GAMEDATA_MANIFEST_PATH` (`manifest-service.ts`) and the
  // envelope shape of the real shipped files (`content/q2_community_content/*/manifest.json`).
  // `includeR1q2` false (the default): byte-identical to the envelope every existing caller reads.
  routes.set(
    '/engines/manifest.json',
    jsonRoute(
      r1q2Engine
        ? {
            schemaVersion: 1,
            packages: [
              manifestPackage(engine, { kind: 'engine', engine: 'q2pro', arch: 'x86_64' }),
              manifestPackage(r1q2Engine, { kind: 'engine', engine: 'r1q2', arch: 'x86' }),
            ],
            pinned: { q2pro: engine.id, r1q2: r1q2Engine.id },
          }
        : {
            schemaVersion: 1,
            packages: [
              manifestPackage(engine, { kind: 'engine', engine: 'q2pro', arch: 'x86_64' }),
            ],
            pinned: { q2pro: engine.id },
          },
    ),
  )
  routes.set(
    '/gamedata/manifest.json',
    jsonRoute({
      schemaVersion: 1,
      packages: [
        manifestPackage(demo, { kind: 'gamedata', role: 'demo' }),
        manifestPackage(pointRelease, { kind: 'gamedata', role: 'point-release' }),
      ],
    }),
  )
  for (const pkg of packages) {
    routes.set(`/packages/${pkg.fileName}`, archiveRoute(pkg.path))
    routes.set(`/mirror/${pkg.fileName}`, archiveRoute(pkg.path))
  }
  if (modsInstall) {
    // Story 190 D7: the mod catalog + its packages. The primary URL is deliberately never routed
    // (404 from the request log's point of view); the mirror serves. `fixturebad`'s bytes differ
    // from its manifest SHA256 on both URLs.
    const mods = buildModsInstallPackages()
    routes.set(
      '/mods/manifest.json',
      jsonRoute({ schemaVersion: 1, entries: modsInstallManifestEntries(mods, baseUrl) }),
    )
    for (const pkg of mods.packages) {
      routes.set(`/mirror/${pkg.fileName}`, archiveRoute(pkg.path, pkg.corrupt, 150))
    }
  }
  if (modsUpdate) {
    // Story 194 D4: newer pinned versions of opentdm (valid package) and action (package bytes that do not
    // match the manifest SHA256). Every package request is visible in `requested` (primary + mirror).
    const mods = buildModsUpdatePackages()
    routes.set(
      '/mods/manifest.json',
      jsonRoute({ schemaVersion: 1, entries: modsUpdateManifestEntries(mods, baseUrl) }),
    )
    for (const pkg of Object.values(mods)) {
      routes.set(`/mirror/${pkg.fileName}`, archiveRoute(pkg.path, false, 150))
    }
  }
  if (modsReplays) {
    // Story 193 D2: a catalog for the Demos tab's "mod missing" install offer - see
    // `modsReplaysManifestEntries()`. `withOpentdm` false leaves the `opentdm` entry out.
    const pkg = buildModsReplaysPackage()
    routes.set(
      '/mods/manifest.json',
      jsonRoute({
        schemaVersion: 1,
        entries: modsReplaysManifestEntries(pkg, baseUrl, modsReplays.withOpentdm),
      }),
    )
    routes.set(`/mirror/${pkg.fileName}`, archiveRoute(pkg.path, false, 150))
  }
  if (bleedingEdgeVersion !== undefined) {
    routes.set('/packages/version.txt', (response) => {
      const bytes = Buffer.from(`${bleedingEdgeVersion}\n`, 'utf8')
      response.writeHead(200, { 'content-type': 'text/plain', 'content-length': bytes.byteLength })
      response.end(bytes)
    })
  }

  return {
    baseUrl,
    packages,
    requested,
    /** Sum of the three archives' real sizes - the figure the confirm step must state (AC4). */
    totalSizeBytes: packages.reduce((total, pkg) => total + pkg.sizeBytes, 0),
    close: () =>
      new Promise((resolve) => {
        server.closeAllConnections?.()
        server.close(() => resolve())
      }),
  }
}

// --- story 088 D6: the fixture "store installations" the retail-import flow copies from ----------
//
// `scripts/flows/bootstrap-retail-import.mjs` needs two detected Steam/GOG installations that
// genuinely exist on disk: the job re-verifies the chosen source's paks before copying and then
// copies the real bytes through `assemble.ts`'s allowlist, so nothing here can be a stub. What CAN
// be avoided is writing 184 MB of content - the launcher's retail check is a SIZE comparison
// (`RETAIL_PAK_SIZES`, `src/shared/constants.ts`), so every pak below is created empty and then
// `truncateSync`d to its exact retail length (story 088's own "Decided during refine" note:
// "Fixture paks are created with `truncate` at the exact retail sizes, not by writing bytes ... a
// 184 MB fixture costs metadata, not I/O"). The copy the job performs afterwards is of course real.
//
// Two installations, deliberately different verdicts, because one wizard run has to show both
// halves of the picker at once (AC2 "identified by its store and its path", AC3 "listed but not
// selectable, with the reason"):
//
//   gog   - `baseq2/pak0.pak` at the 8 MiB demo size instead of the retail one, `pak1.pak` correct.
//           The ONLY defect is pak0's size, so its verdict is exactly `pak0SizeMismatch` and not
//           some incidental "pak1 is missing" instead.
//   steam - pak0/pak1/pak2 all at their exact `RETAIL_PAK_SIZES` length: verified, and the one the
//           flow installs from.
//
// Both also carry payload the allowlist must DISCARD - `ctf/`, `xatrix/`, `rogue/`, a `pak3.pak`
// and a loose `quake2.exe` - so AC7 ("no ctf/xatrix/rogue directory is created even if the source
// installation has one") is a claim about real, rejected input rather than about input that never
// existed. Neither has `baseq2/video` or `baseq2/players`, which is also what makes the confirm
// step's video/players toggle render disabled with its reason (story 088's binding user decision).

/**
 * Mirrors src/shared/constants.ts:54 (`RETAIL_PAK_SIZES`) - classic Quake II 3.20, the sizes
 * `inspectRetailSource` compares against. Exported so the flow can assert the copied files' sizes
 * against the same numbers rather than re-deriving them from the fixture it just wrote.
 */
export const RETAIL_PAK_SIZES = {
  'pak0.pak': 183_997_730,
  'pak1.pak': 12_992_754,
  'pak2.pak': 45_055,
}

/** The unverified fixture's deliberately wrong `pak0.pak` length: the 8 MiB demo pak0 size, the
 * single most plausible "this is not retail" case a user could actually have. */
export const UNVERIFIED_PAK0_BYTES = 8 * 1024 * 1024

/** `baseq2/pak3.pak` - present in both sources, in the allowlist of neither. */
const RETAIL_SOURCE_STRAY_PAK = 'pak3.pak'

/** A loose file in the source root that must not be copied either. */
const RETAIL_SOURCE_STRAY_FILE = 'quake2.exe'

/** Mission-pack directories AC7 forbids in the target; both fixture sources ship all three. */
const RETAIL_SOURCE_DISCARDED_DIRS = ['ctf', 'xatrix', 'rogue']

/** Where the two fixture store installations live - siblings under the bootstrap fixture root. */
function retailSourceRoot(store) {
  return join(bootstrapFixtureRoot(), 'store-sources', store)
}

/** The folder `scripts/flows/bootstrap-retail-import.mjs` installs into - its own sibling of
 * `bootstrapTargetDir()`/`bootstrapR1q2TargetDir()`, so the three bootstrap flows never race over
 * one directory. Fresh and empty: target warnings are already proven by `bootstrap-wizard.mjs`. */
export function bootstrapRetailTargetDir() {
  return join(bootstrapFixtureRoot(), 'target', 'Retail Import')
}

/** Fresh, empty target folder for the retail-import flow - deletes any leftover from a previous run. */
export function writeBootstrapRetailTargetDir() {
  const target = assertInside(UI_VERIFY_ROOT, bootstrapRetailTargetDir(), 'bootstrap retail target')
  rmDirBestEffort(target)
  mkdirSync(target, { recursive: true })
  return target
}

/** Story 089 D6: the folder `scripts/flows/bootstrap-existing-folder.mjs` installs into - its own
 * sibling of `bootstrapTargetDir()`/`bootstrapRetailTargetDir()`, so the bootstrap flows never race
 * over one directory. Fresh and empty: target warnings are already proven by `bootstrap-wizard.mjs`. */
export function bootstrapExistingFolderTargetDir() {
  return join(bootstrapFixtureRoot(), 'target', 'Existing Folder Import')
}

/** Fresh, empty target folder for the existing-folder flow - deletes any leftover from a previous run. */
export function writeBootstrapExistingFolderTargetDir() {
  const target = assertInside(
    UI_VERIFY_ROOT,
    bootstrapExistingFolderTargetDir(),
    'bootstrap existing-folder target',
  )
  rmDirBestEffort(target)
  mkdirSync(target, { recursive: true })
  return target
}

/** An empty file stretched to `sizeBytes` - metadata only, no content written (see above). */
export function writeSizedFile(path, sizeBytes) {
  writeFileSync(path, '')
  truncateSync(path, sizeBytes)
}

/**
 * Mirrors `inspectRetailSource` (`src/main/modules/downloads/bootstrap/retail-source.ts`) closely
 * enough to describe THESE fixtures: every field is read off the files just written, so the
 * `DetectedRetailSource[]` handed to the app through `Q2L_UI_HARNESS_STORE_SOURCES` states facts
 * about real bytes on disk rather than a hand-authored verdict. That matters beyond tidiness: the
 * job re-checks `inspection.verified` before copying (`verifyCopySource`, `bootstrap/job.ts`), so a
 * fixture whose injected verdict disagreed with its own files would either fail the run or - worse -
 * make a passing run prove nothing.
 */
function inspectFixtureRetailSource(rootPath) {
  const baseq2 = join(rootPath, 'baseq2')
  const inspectPak = (name) => {
    const path = join(baseq2, name)
    if (!existsSync(path)) return { exists: false, sizeBytes: null, matchesRetailSize: false }
    const sizeBytes = statSync(path).size
    return { exists: true, sizeBytes, matchesRetailSize: sizeBytes === RETAIL_PAK_SIZES[name] }
  }

  const pak0 = inspectPak('pak0.pak')
  const pak1 = inspectPak('pak1.pak')
  const pak2 = inspectPak('pak2.pak')

  let unverifiedReason
  if (!existsSync(baseq2)) unverifiedReason = 'bootstrap.retailSource.baseDirMissing'
  else if (!pak0.exists) unverifiedReason = 'bootstrap.retailSource.pak0Missing'
  else if (!pak0.matchesRetailSize) unverifiedReason = 'bootstrap.retailSource.pak0SizeMismatch'
  else if (!pak1.exists) unverifiedReason = 'bootstrap.retailSource.pak1Missing'
  else if (!pak1.matchesRetailSize) unverifiedReason = 'bootstrap.retailSource.pak1SizeMismatch'

  return {
    rootPath,
    pak0,
    pak1,
    pak2,
    verified: unverifiedReason === undefined,
    ...(unverifiedReason ? { unverifiedReason } : {}),
    hasVideo: existsSync(join(baseq2, 'video')),
    hasPlayers: existsSync(join(baseq2, 'players')),
  }
}

/** One fixture store installation on disk: `baseq2` with the requested pak sizes, plus the payload
 * the allowlist has to discard. */
function writeRetailSourceTree(store, { pak0Bytes, pak1Bytes, pak2Bytes }) {
  const root = assertInside(UI_VERIFY_ROOT, retailSourceRoot(store), `retail source ${store}`)
  rmDirBestEffort(root)

  const baseq2 = join(root, 'baseq2')
  mkdirSync(baseq2, { recursive: true })
  writeSizedFile(join(baseq2, 'pak0.pak'), pak0Bytes)
  writeSizedFile(join(baseq2, 'pak1.pak'), pak1Bytes)
  if (pak2Bytes !== undefined) writeSizedFile(join(baseq2, 'pak2.pak'), pak2Bytes)
  writeSizedFile(join(baseq2, RETAIL_SOURCE_STRAY_PAK), 4096)
  writeFileSync(join(root, RETAIL_SOURCE_STRAY_FILE), 'not the launcher’s engine\n', 'utf8')
  for (const dir of RETAIL_SOURCE_DISCARDED_DIRS) {
    mkdirSync(join(root, dir), { recursive: true })
    writeSizedFile(join(root, dir, 'pak0.pak'), 2048)
  }

  return root
}

/**
 * Writes both fixture store installations and returns them as the `DetectedRetailSource[]` the
 * `Q2L_UI_HARNESS_STORE_SOURCES` override expects (`resolveDetectedRetailSourcesOverride`,
 * `src/main/modules/downloads/harness.ts`) - `{ source, rootPath, inspection }` per entry, the exact
 * shape `listDetectedRetailSources` would have produced had a real Steam/GOG library been there.
 *
 * The GOG (unverified) entry comes FIRST on purpose: it puts the not-selectable row at the top of
 * the picker, where a list that silently dropped it would be most obvious, and it makes the
 * wizard's "default to the first verified source" convenience (`selectDataSource`,
 * `BootstrapWizard.tsx`) genuinely skip a row rather than trivially land on row 0.
 */
export function writeBootstrapStoreSources() {
  const gogRoot = writeRetailSourceTree('gog', {
    pak0Bytes: UNVERIFIED_PAK0_BYTES,
    pak1Bytes: RETAIL_PAK_SIZES['pak1.pak'],
  })
  const steamRoot = writeRetailSourceTree('steam', {
    pak0Bytes: RETAIL_PAK_SIZES['pak0.pak'],
    pak1Bytes: RETAIL_PAK_SIZES['pak1.pak'],
    pak2Bytes: RETAIL_PAK_SIZES['pak2.pak'],
  })

  return [
    { source: 'gog', rootPath: gogRoot, inspection: inspectFixtureRetailSource(gogRoot) },
    { source: 'steam', rootPath: steamRoot, inspection: inspectFixtureRetailSource(steamRoot) },
  ]
}

// --- story 089 D6: the hand-picked "existing folder" game-data source ---------------------------
//
// `scripts/flows/bootstrap-existing-folder.mjs` needs a plain folder on disk - deliberately NOT one
// of `writeBootstrapStoreSources()`'s "detected store" fixtures, since the whole point of this data
// source is that the launcher never found it on its own. Same truncate-to-exact-size trick as
// `writeRetailSourceTree` above (no real 184 MB written), and the same discarded payload
// (`ctf`/`xatrix`/`rogue`, a stray `pak3.pak`, a loose file) so AC7's "no forbidden directory is
// created even though the source has one" has something real to prove against.

/** Where the fixture "existing folder" source lives - a sibling of `retailSourceRoot()`'s "store
 * sources" dir, but its own top-level name: this folder was never detected, so it must not read as
 * one of the detected-store fixtures even by its path. */
function existingFolderSourceRoot() {
  return join(bootstrapFixtureRoot(), 'existing-folder-source')
}

export function bootstrapExistingFolderSourceDir() {
  return existingFolderSourceRoot()
}

/**
 * Writes a plain folder with `baseq2/pak0.pak` (+`pak1.pak` for a retail folder), sized exactly for
 * the case requested - `retail: true` for a `kind: 'retail'` verdict (both paks at their exact
 * `RETAIL_PAK_SIZES` length), `retail: false` for a `kind: 'demo'` verdict (only a demo-sized pak0,
 * no pak1 at all - `inspectGameDataSource` reports `kind: 'demo'` whenever pak0 exists but the pair
 * does not verify as retail). Also writes the same discarded payload
 * `writeRetailSourceTree` writes for the detected-store fixtures - `ctf`/`xatrix`/`rogue`,
 * `pak3.pak`, a loose `quake2.exe` - so AC7 has real bytes to prove were never copied.
 */
export function writeBootstrapExistingFolderSource({ retail }) {
  const root = assertInside(UI_VERIFY_ROOT, existingFolderSourceRoot(), 'existing-folder source')
  rmDirBestEffort(root)

  const baseq2 = join(root, 'baseq2')
  mkdirSync(baseq2, { recursive: true })
  writeSizedFile(
    join(baseq2, 'pak0.pak'),
    retail ? RETAIL_PAK_SIZES['pak0.pak'] : UNVERIFIED_PAK0_BYTES,
  )
  if (retail) writeSizedFile(join(baseq2, 'pak1.pak'), RETAIL_PAK_SIZES['pak1.pak'])
  writeSizedFile(join(baseq2, RETAIL_SOURCE_STRAY_PAK), 4096)
  writeFileSync(join(root, RETAIL_SOURCE_STRAY_FILE), 'not the launcher’s engine\n', 'utf8')
  for (const dir of RETAIL_SOURCE_DISCARDED_DIRS) {
    mkdirSync(join(root, dir), { recursive: true })
    writeSizedFile(join(root, dir, 'pak0.pak'), 2048)
  }

  return root
}

/**
 * Story 089 D5: the AC5 counterpart to `writeBootstrapExistingFolderSource({ retail: false })` -
 * a folder that exists but has no `baseq2/pak0.pak` at all, so `inspectGameDataSource` reports
 * `kind: 'unusable'` with `bootstrap.gameDataSource.baseDirMissing` (no `baseq2` directory
 * whatsoever - the simplest, least ambiguous way to be pak0-less). Same root as the retail/demo
 * fixture (`existingFolderSourceRoot()`) so the flow needs no second `Q2L_UI_PICK_FOLDER` path.
 */
export function writeBootstrapExistingFolderUnusableSource() {
  const root = assertInside(UI_VERIFY_ROOT, existingFolderSourceRoot(), 'existing-folder source')
  rmDirBestEffort(root)
  mkdirSync(root, { recursive: true })
  return root
}

// --- story 240: the subfolder-proposal fixture ----------------------------------------------------

/** The two folders `scripts/flows/bootstrap-target-subfolder.mjs` picks as a target location. */
export function bootstrapSubfolderDirs() {
  const root = join(bootstrapFixtureRoot(), 'target', 'Subfolder')
  return { parent: join(root, 'parent'), empty: join(root, 'empty') }
}

/**
 * A parent holding a NON-empty `<occupiedName>` subfolder (so the proposal has to pick the
 * ` (2)` name) plus a separate empty directory (the install-here case). Recreated on every run.
 */
export function writeBootstrapSubfolderDirs(occupiedName) {
  const { parent, empty } = bootstrapSubfolderDirs()
  for (const dir of [parent, empty]) {
    rmDirBestEffort(assertInside(UI_VERIFY_ROOT, dir, 'bootstrap subfolder fixture'))
  }
  mkdirSync(join(parent, occupiedName), { recursive: true })
  writeFileSync(join(parent, occupiedName, 'user-notes.txt'), 'already here\n', 'utf8')
  mkdirSync(empty, { recursive: true })
  return { parent, empty }
}
